apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: henrybell-kcc-demo-bucket-1
  namespace: config-control
spec:
  location: us-central1
  uniformBucketLevelAccess: true
