apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/henrybell/henrybell-kcc-config
    branch: main
    dir: sync-resources
    auth: none
